### ISSUE TITLE
How do we change the dividers on the files tab?

### ISSUE THREAD

**Issue by modMars** [CreArts-Community/CreArts-Obsidian-Vault#5]
I thought it was a plugin but is it a feature baked into the vault's custom theme?

To be more specific i mean these tags 'General', 'Private', 'Public', 'Assets', 'Other'

![imagen](https://github.com/CreArts-Community/CreArts-Obsidian-Vault/assets/90658669/5e658831-2ae7-4b43-ac44-adec961f3598)

**Comment by CorellanStoma** [comment]
Hi, yeah these are added via CSS Snippet, basically, the headers are defined in the addon-folder-headers.css file and can be customized there, the order of the folders is defined with the folder name and the respective numbering (numbers from 0-9 are possible). 

The numbers are then hidden with the addon-folder-hide-numbers.css file.

The addon-folder-descriptions.css file can be used to give the folders descriptions.

The adjustments are divided into:
* **addon-folder-hide-numbers.css**
* **addon-folder-headers.css**
* **addon-folder-descriptions.css**

I mainly work with pseudo elements, with a little CSS knowledge you should be able to modify it.

([some more infos here](https://github.com/CreArts-Community/CreArts-Obsidian-Vault/issues/4))
